/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motorph;

import com.mycompany.motorph.data.LeaveDataManager;
import com.mycompany.motorph.model.Leave;
import com.mycompany.motorph.model.LeaveRequest;
import com.opencsv.exceptions.CsvValidationException;
import javax.swing.table.DefaultTableModel;
import java.awt.HeadlessException;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author JustAMob
 */
public class LeaveTablePage extends javax.swing.JFrame {

    DefaultTableModel dm;

    /**
     * Creates new form AdminUI
     *
     * @throws java.io.IOException
     */
    public LeaveTablePage() throws IOException {
        initComponents();
        populateLeaveRequestTable();

    }

    private void populateLeaveRequestTable() {
        DefaultTableModel model = LeaveRequest.getLeaveRequestTableModel();
        jTableLeaveRequest.setModel(model);

    }

    private void approveOrDecline(String approveOrDecline) {
        int selectedRow = jTableLeaveRequest.getSelectedRow();

        LeaveRequest leaveRequest = new LeaveRequest();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Please select a request to update.");
        }

        DefaultTableModel model = (DefaultTableModel) jTableLeaveRequest.getModel();
        try {
            model.setValueAt(approveOrDecline, selectedRow, 5);
            model.setValueAt(jTextFieldLeaveRemarks.getText(), selectedRow, 6);

            int employeeID = (int) jTableLeaveRequest.getValueAt(selectedRow, 0);
            String status = (String) jTableLeaveRequest.getValueAt(selectedRow, 5);
            String remarks = (String) jTableLeaveRequest.getValueAt(selectedRow, 6);

            // Create the updated Leave Request object
            LeaveRequest updatedLeaveRequest = new LeaveRequest(employeeID, status, remarks);

            // Update the CSV file with the new employee information
            leaveRequest.updateLeaveRequest(updatedLeaveRequest);

            JOptionPane.showMessageDialog(null, "Employee information updated successfully!");

        } catch (HeadlessException ex) {
            JOptionPane.showMessageDialog(null, "An error occurred while updating the table.");
        }
    }

    public void refreshTable() {
        DefaultTableModel model = (DefaultTableModel) jTableLeaveRequest.getModel();
        model.setRowCount(0); // Clear table before adding new data

        List<LeaveRequest> leaves = LeaveRequest.getLeaveRequestList(); // Load from Employee_leave_requests.csv
        for (LeaveRequest leave : leaves) {
            model.addRow(new Object[]{
                leave.getLeaveRequestID(),
                leave.getName(),
                leave.getStartDate(),
                leave.getEndDate(),
                leave.getLeaveRequestPurpose(),
                leave.getLeaveStatus(),
                leave.getLeaveRemarks()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedLeaveRequests = new javax.swing.JTabbedPane();
        jPanelLeaveRequests = new javax.swing.JPanel();
        jComboBoxLeaveRequest = new javax.swing.JComboBox<>();
        jLabelRequests = new javax.swing.JLabel();
        jTabbedPaneLeaveRequests = new javax.swing.JTabbedPane();
        jPanelAllRequests = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLeaveRequest = new javax.swing.JTable();
        jPanelApprovedLeaveRequests = new javax.swing.JPanel();
        jPanelDeclinedLeaveRequests = new javax.swing.JPanel();
        jPanelPendingLeaveRequests = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldLeaveEmpID = new javax.swing.JTextField();
        jTextFieldLeaveName = new javax.swing.JTextField();
        jTextFieldLeaveStartDate = new javax.swing.JTextField();
        jTextFieldLeaveEndDate = new javax.swing.JTextField();
        jTextFieldLeavePurpose = new javax.swing.JTextField();
        jTextFieldLeaveStatus = new javax.swing.JTextField();
        jTextFieldLeaveRemarks = new javax.swing.JTextField();
        jButtonApproveLeave = new javax.swing.JButton();
        jButtonDeclineLeave = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelLeaveRequests.setBackground(new java.awt.Color(77, 77, 105));

        jComboBoxLeaveRequest.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"All Requests", "Approved", "Declined", "Pending"}));
        jComboBoxLeaveRequest.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxLeaveRequestItemStateChanged(evt);
            }
        });
        jComboBoxLeaveRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxLeaveRequestMouseClicked(evt);
            }
        });
        jComboBoxLeaveRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxLeaveRequestActionPerformed(evt);
            }
        });
        jComboBoxLeaveRequest.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxLeaveRequestPropertyChange(evt);
            }
        });

        jLabelRequests.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRequests.setText("Requests");

        jTableLeaveRequest.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "Employee ID", "Name", "Start Date", "End Date", "Purpose", "Status", "Leave Remarks"
                }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTableLeaveRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLeaveRequestMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableLeaveRequest);

        javax.swing.GroupLayout jPanelAllRequestsLayout = new javax.swing.GroupLayout(jPanelAllRequests);
        jPanelAllRequests.setLayout(jPanelAllRequestsLayout);
        jPanelAllRequestsLayout.setHorizontalGroup(
                jPanelAllRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAllRequestsLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanelAllRequestsLayout.setVerticalGroup(
                jPanelAllRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAllRequestsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneLeaveRequests.addTab("All Requests", jPanelAllRequests);

        javax.swing.GroupLayout jPanelApprovedLeaveRequestsLayout = new javax.swing.GroupLayout(jPanelApprovedLeaveRequests);
        jPanelApprovedLeaveRequests.setLayout(jPanelApprovedLeaveRequestsLayout);
        jPanelApprovedLeaveRequestsLayout.setHorizontalGroup(
                jPanelApprovedLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanelApprovedLeaveRequestsLayout.setVerticalGroup(
                jPanelApprovedLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 493, Short.MAX_VALUE)
        );

        jTabbedPaneLeaveRequests.addTab("Approved", jPanelApprovedLeaveRequests);

        javax.swing.GroupLayout jPanelDeclinedLeaveRequestsLayout = new javax.swing.GroupLayout(jPanelDeclinedLeaveRequests);
        jPanelDeclinedLeaveRequests.setLayout(jPanelDeclinedLeaveRequestsLayout);
        jPanelDeclinedLeaveRequestsLayout.setHorizontalGroup(
                jPanelDeclinedLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanelDeclinedLeaveRequestsLayout.setVerticalGroup(
                jPanelDeclinedLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 493, Short.MAX_VALUE)
        );

        jTabbedPaneLeaveRequests.addTab("Declined", jPanelDeclinedLeaveRequests);

        javax.swing.GroupLayout jPanelPendingLeaveRequestsLayout = new javax.swing.GroupLayout(jPanelPendingLeaveRequests);
        jPanelPendingLeaveRequests.setLayout(jPanelPendingLeaveRequestsLayout);
        jPanelPendingLeaveRequestsLayout.setHorizontalGroup(
                jPanelPendingLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanelPendingLeaveRequestsLayout.setVerticalGroup(
                jPanelPendingLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 493, Short.MAX_VALUE)
        );

        jTabbedPaneLeaveRequests.addTab("Pending", jPanelPendingLeaveRequests);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Employee ID: ");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Start Date:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("End Date:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Purpose:");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Status:");

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Remarks:");

        jTextFieldLeaveEmpID.setEditable(false);
        jTextFieldLeaveEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLeaveEmpIDActionPerformed(evt);
            }
        });

        jTextFieldLeaveName.setEditable(false);

        jTextFieldLeaveStartDate.setEditable(false);

        jTextFieldLeaveEndDate.setEditable(false);

        jTextFieldLeavePurpose.setEditable(false);

        jTextFieldLeaveStatus.setEditable(false);

        jButtonApproveLeave.setBackground(new java.awt.Color(102, 255, 102));
        jButtonApproveLeave.setText("Approve");
        jButtonApproveLeave.setActionCommand("ApproveLeave");
        jButtonApproveLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApproveLeaveActionPerformed(evt);
            }
        });

        jButtonDeclineLeave.setBackground(new java.awt.Color(255, 51, 51));
        jButtonDeclineLeave.setText("Decline");
        jButtonDeclineLeave.setActionCommand("DeclineLeave");
        jButtonDeclineLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeclineLeaveActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/motorcycleWhite.png"))); // NOI18N
        jLabel16.setText("MotorPH");

        javax.swing.GroupLayout jPanelLeaveRequestsLayout = new javax.swing.GroupLayout(jPanelLeaveRequests);
        jPanelLeaveRequests.setLayout(jPanelLeaveRequestsLayout);
        jPanelLeaveRequestsLayout.setHorizontalGroup(
                jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLeaveRequestsLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jButtonApproveLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jButtonDeclineLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40))
                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel10)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLeaveName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel11)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLeaveStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel12)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLeaveEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel13)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLeavePurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel14)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLeaveStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel15)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(jTextFieldLeaveRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                                .addComponent(jLabel9)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jTextFieldLeaveEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                .addContainerGap()
                                                                .addComponent(jLabel16)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                .addComponent(jLabelRequests)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxLeaveRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTabbedPaneLeaveRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(334, Short.MAX_VALUE))
        );
        jPanelLeaveRequestsLayout.setVerticalGroup(
                jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabelRequests)
                                                        .addComponent(jComboBoxLeaveRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)
                                                .addComponent(jTabbedPaneLeaveRequests))
                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(jLabel16)
                                                .addGap(77, 77, 77)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jTextFieldLeaveEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jTextFieldLeaveName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel11)
                                                        .addComponent(jTextFieldLeaveStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel12)
                                                        .addComponent(jTextFieldLeaveEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextFieldLeavePurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanelLeaveRequestsLayout.createSequentialGroup()
                                                                .addGap(8, 8, 8)
                                                                .addComponent(jLabel13)))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel14)
                                                        .addComponent(jTextFieldLeaveStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jTextFieldLeaveRemarks, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanelLeaveRequestsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButtonApproveLeave)
                                                        .addComponent(jButtonDeclineLeave))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );

        jTabbedLeaveRequests.addTab("Leave Requests", jPanelLeaveRequests);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(28, Short.MAX_VALUE)
                                .addComponent(jTabbedLeaveRequests, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedLeaveRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedLeaveRequests.getAccessibleContext().setAccessibleName("Employee Data");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDeclineLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeclineLeaveActionPerformed
        // TODO add your handling code here:
        String status = "Declined";
        approveOrDecline(status);
    }//GEN-LAST:event_jButtonDeclineLeaveActionPerformed

    private void jButtonApproveLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApproveLeaveActionPerformed
        // TODO add your handling code here:
        String status = "Approved";
        approveOrDecline(status);
    }//GEN-LAST:event_jButtonApproveLeaveActionPerformed

    private void jTextFieldLeaveEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLeaveEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLeaveEmpIDActionPerformed

    private void jTableLeaveRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLeaveRequestMouseClicked
        // TODO add your handling code here:
        int i = jTableLeaveRequest.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTableLeaveRequest.getModel();
        jTextFieldLeaveEmpID.setText(model.getValueAt(i, 0).toString());
        jTextFieldLeaveName.setText(model.getValueAt(i, 1).toString());
        jTextFieldLeaveStartDate.setText(model.getValueAt(i, 2).toString());
        jTextFieldLeaveEndDate.setText(model.getValueAt(i, 3).toString());
        jTextFieldLeavePurpose.setText(model.getValueAt(i, 4).toString());
        jTextFieldLeaveStatus.setText(model.getValueAt(i, 5).toString());
        jTextFieldLeaveRemarks.setText(model.getValueAt(i, 6).toString());
    }//GEN-LAST:event_jTableLeaveRequestMouseClicked

    private void jComboBoxLeaveRequestPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxLeaveRequestPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLeaveRequestPropertyChange

    private void jComboBoxLeaveRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxLeaveRequestActionPerformed
        //         TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLeaveRequestActionPerformed

    private void jComboBoxLeaveRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxLeaveRequestMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxLeaveRequestMouseClicked

    private void jComboBoxLeaveRequestItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxLeaveRequestItemStateChanged
        // TODO add your handling code here:
        int tabIndex = jComboBoxLeaveRequest.getSelectedIndex();
        jTabbedPaneLeaveRequests.setSelectedIndex(tabIndex);

        String selectedItem = (String) jComboBoxLeaveRequest.getSelectedItem();

        //       filter(selectedItem);
    }//GEN-LAST:event_jComboBoxLeaveRequestItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveTablePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new LeaveTablePage().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(LeaveTablePage.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonApproveLeave;
    private javax.swing.JButton jButtonDeclineLeave;
    private javax.swing.JComboBox<String> jComboBoxLeaveRequest;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelRequests;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAllRequests;
    private javax.swing.JPanel jPanelApprovedLeaveRequests;
    private javax.swing.JPanel jPanelDeclinedLeaveRequests;
    private javax.swing.JPanel jPanelLeaveRequests;
    private javax.swing.JPanel jPanelPendingLeaveRequests;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedLeaveRequests;
    private javax.swing.JTabbedPane jTabbedPaneLeaveRequests;
    private javax.swing.JTable jTableLeaveRequest;
    private javax.swing.JTextField jTextFieldLeaveEmpID;
    private javax.swing.JTextField jTextFieldLeaveEndDate;
    private javax.swing.JTextField jTextFieldLeaveName;
    private javax.swing.JTextField jTextFieldLeavePurpose;
    private javax.swing.JTextField jTextFieldLeaveRemarks;
    private javax.swing.JTextField jTextFieldLeaveStartDate;
    private javax.swing.JTextField jTextFieldLeaveStatus;
    // End of variables declaration//GEN-END:variables

}
