/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.motorph.ui;

import com.mycompany.motorph.employee.EmployeeInformation;
import com.mycompany.motorph.model.Employee;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.text.ParseException;
import java.util.HashSet;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JMenuItem;

/**
 * Main Menu for the MotorPH application.
 * <p>
 * Provides navigation to employee search and leave management.
 *
 * @author Lance
 */
class MainMenu extends javax.swing.JFrame {

    // Constants for button coloring changes
    private static final java.awt.Color LIGHT_BLUE = new java.awt.Color(203, 203, 239);
    private static final java.awt.Color WHITE = new java.awt.Color(255, 255, 255);
    private static final java.awt.Color RED = new java.awt.Color(191, 47, 47);

    private int employeeNumber;
    private String userRole;

    /**
     * Creates new form MotorPHMainMenu
     */
    public MainMenu(int employeeNumber, String userRole) {
        this.employeeNumber = employeeNumber;
        this.userRole = userRole;
        initComponents();
        configureMenu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        lblMotorPhHeader = new javax.swing.JLabel();
        lblMainMenuHeader = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnApplyForLeave = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnComputePayroll = new javax.swing.JButton();
        btnSearchAnEmployee = new javax.swing.JButton();
        btnAddNewEmployee = new javax.swing.JButton();
        btnManageLeaveRequests = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Payroll System Main Menu");
        setResizable(false);

        pnlMain.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain.setMaximumSize(null);

        lblMotorPhHeader.setBackground(new java.awt.Color(255, 255, 255));
        lblMotorPhHeader.setFont(new java.awt.Font("Leelawadee", 1, 18)); // NOI18N
        lblMotorPhHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMotorPhHeader.setText("MotorPH Payroll System");
        lblMotorPhHeader.setOpaque(true);

        lblMainMenuHeader.setBackground(new java.awt.Color(223, 54, 54));
        lblMainMenuHeader.setFont(new java.awt.Font("Leelawadee", 1, 16)); // NOI18N
        lblMainMenuHeader.setForeground(new java.awt.Color(255, 255, 255));
        lblMainMenuHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMainMenuHeader.setText("Main Menu");
        lblMainMenuHeader.setOpaque(true);

        btnViewProfile.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnViewProfile.setText("View Profile");
        btnViewProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnViewProfile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewProfile.setFocusable(false);
        btnViewProfile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewProfileMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewProfileMouseExited(evt);
            }
        });
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.setFocusable(false);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnApplyForLeave.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnApplyForLeave.setText("Apply for Leave");
        btnApplyForLeave.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnApplyForLeave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnApplyForLeave.setFocusable(false);
        btnApplyForLeave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnApplyForLeaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnApplyForLeaveMouseExited(evt);
            }
        });
        btnApplyForLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyForLeaveActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setToolTipText("");
        btnLogout.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.setFocusable(false);
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogoutMouseExited(evt);
            }
        });
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnComputePayroll.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnComputePayroll.setText("Compute Payroll");
        btnComputePayroll.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnComputePayroll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComputePayroll.setFocusable(false);
        btnComputePayroll.setMaximumSize(new java.awt.Dimension(62, 16));
        btnComputePayroll.setMinimumSize(new java.awt.Dimension(62, 16));
        btnComputePayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComputePayrollMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComputePayrollMouseExited(evt);
            }
        });
        btnComputePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputePayrollActionPerformed(evt);
            }
        });

        btnSearchAnEmployee.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnSearchAnEmployee.setText("Search an Employee");
        btnSearchAnEmployee.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnSearchAnEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchAnEmployee.setFocusable(false);
        btnSearchAnEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSearchAnEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSearchAnEmployeeMouseExited(evt);
            }
        });
        btnSearchAnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchAnEmployeeActionPerformed(evt);
            }
        });

        btnAddNewEmployee.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnAddNewEmployee.setText("Add New Employee");
        btnAddNewEmployee.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnAddNewEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddNewEmployee.setFocusable(false);
        btnAddNewEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewEmployeeMouseExited(evt);
            }
        });
        btnAddNewEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmployeeActionPerformed(evt);
            }
        });

        btnManageLeaveRequests.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        btnManageLeaveRequests.setText("Manage Leave Requests");
        btnManageLeaveRequests.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        btnManageLeaveRequests.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManageLeaveRequests.setFocusable(false);
        btnManageLeaveRequests.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnManageLeaveRequestsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnManageLeaveRequestsMouseExited(evt);
            }
        });
        btnManageLeaveRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLeaveRequestsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMainMenuHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblMotorPhHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnComputePayroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSearchAnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnViewProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(btnApplyForLeave, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnManageLeaveRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnAddNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMotorPhHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMainMenuHeader)
                .addGap(15, 15, 15)
                .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnComputePayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnApplyForLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(btnSearchAnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnManageLeaveRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(btnAddNewEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Opens the employee profile view page.
     */
    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        EmployeeInformation employeeInformation = new EmployeeInformation();

        try {
            // Load all employees first
            List<Employee> employees = employeeInformation.getAllEmployees();
            Employee employee = employeeInformation.findEmployeeByNumber(employees, employeeNumber);

            if (employee != null) {
                // Open the Employee Information Frame with the Employee object
                new EmployeeViewProfileFrame(employee).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Employee not found. Please check the Employee Number.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        } catch (IOException | CsvValidationException | ParseException ex) {
            JOptionPane.showMessageDialog(this,
                    "Error retrieving employee information: " + ex.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnViewProfileActionPerformed

    /**
     * Handles the action event of the manage leave button to open the manage
     * leave page.
     */
    private void btnApplyForLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyForLeaveActionPerformed
        // Open ManageLeaveMenu
        new LeaveApplicationPage(employeeNumber).setVisible(true);
    }//GEN-LAST:event_btnApplyForLeaveActionPerformed

    /**
     * Handles mouse hover event on the search employee button by changing its
     * background color.
     */
    private void btnViewProfileMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewProfileMouseEntered
        btnViewProfile.setBackground(LIGHT_BLUE);
    }//GEN-LAST:event_btnViewProfileMouseEntered

    /**
     * Handles mouse exit event on the search employee button by resetting its
     * background color.
     */
    private void btnViewProfileMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewProfileMouseExited
        btnViewProfile.setBackground(WHITE);
    }//GEN-LAST:event_btnViewProfileMouseExited

    /**
     * Handles mouse hover event on the manage leave button by changing its
     * background color.
     */
    private void btnApplyForLeaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyForLeaveMouseEntered
        btnApplyForLeave.setBackground(LIGHT_BLUE);
    }//GEN-LAST:event_btnApplyForLeaveMouseEntered

    /**
     * Handles mouse exit event on the manage leave button by resetting its
     * background color.
     */
    private void btnApplyForLeaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnApplyForLeaveMouseExited
        btnApplyForLeave.setBackground(WHITE);
    }//GEN-LAST:event_btnApplyForLeaveMouseExited

    /**
     * Handles mouse exit event on the exit button by resetting its background
     * color.
     */
    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        btnExit.setBackground(WHITE);
    }//GEN-LAST:event_btnExitMouseExited

    /**
     * Handles mouse hover event on the exit button by changing its background
     * color.
     */
    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        btnExit.setBackground(RED);
    }//GEN-LAST:event_btnExitMouseEntered

    /**
     * Handles the action event of the exit button to exit the application.
     */
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Exit the application
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * Handles the action event of the "Logout" button. Opens the login page and
     * closes the current main menu.
     */
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        logout();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * Handles mouse hover event on the "Logout" button by changing its
     * background color.
     */
    private void btnLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseEntered
        btnLogout.setBackground(LIGHT_BLUE);
    }//GEN-LAST:event_btnLogoutMouseEntered

    /**
     * Handles mouse exit event on the "Logout" button by resetting its
     * background color.
     */
    private void btnLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseExited
        btnLogout.setBackground(WHITE);
    }//GEN-LAST:event_btnLogoutMouseExited

    /**
     * Opens the payroll computation page.
     */
    private void btnComputePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputePayrollActionPerformed
        new PayrollComputationFrame(employeeNumber).setVisible(true);
    }//GEN-LAST:event_btnComputePayrollActionPerformed

    /**
     * Handles mouse hover event on the "Compute" button by changing its
     * background color.
     */
    private void btnComputePayrollMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputePayrollMouseEntered
        btnComputePayroll.setBackground(LIGHT_BLUE);
    }//GEN-LAST:event_btnComputePayrollMouseEntered

    /**
     * Handles mouse exit event on the "Compute" button by resetting its
     * background color.
     */
    private void btnComputePayrollMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComputePayrollMouseExited
        btnComputePayroll.setBackground(WHITE);
    }//GEN-LAST:event_btnComputePayrollMouseExited

    private void btnSearchAnEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchAnEmployeeMouseEntered
        btnSearchAnEmployee.setBackground(LIGHT_BLUE);
    }//GEN-LAST:event_btnSearchAnEmployeeMouseEntered

    private void btnSearchAnEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchAnEmployeeMouseExited
        btnSearchAnEmployee.setBackground(WHITE);
    }//GEN-LAST:event_btnSearchAnEmployeeMouseExited

    private void btnAddNewEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewEmployeeMouseEntered
        btnAddNewEmployee.setBackground(LIGHT_BLUE);
    }//GEN-LAST:event_btnAddNewEmployeeMouseEntered

    private void btnAddNewEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewEmployeeMouseExited
        btnAddNewEmployee.setBackground(WHITE);
    }//GEN-LAST:event_btnAddNewEmployeeMouseExited

    private void btnManageLeaveRequestsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageLeaveRequestsMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageLeaveRequestsMouseEntered

    private void btnManageLeaveRequestsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManageLeaveRequestsMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageLeaveRequestsMouseExited

    private void btnSearchAnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchAnEmployeeActionPerformed
        // TODO add your handling code here:
        EmployeeSearchPage searchPage = new EmployeeSearchPage();

        if ("Admin".equals(userRole)) {

            JMenuItem mniUpdateInformation = new JMenuItem("Update Information");
            mniUpdateInformation.addActionListener(e -> searchPage.mniUpdateInformationActionPerformed(new java.awt.event.ActionEvent(this, ActionEvent.ACTION_PERFORMED, null)));

            JMenuItem mniComputePayroll = new JMenuItem("Compute Payroll");
            mniComputePayroll.addActionListener(e -> searchPage.mniComputePayrollActionPerformed(new java.awt.event.ActionEvent(this, ActionEvent.ACTION_PERFORMED, null)));

            // Pass the menu items into the EmployeeSearchPage
            searchPage.setPopupMenuItems(mniUpdateInformation, mniComputePayroll);
        } else if ("IT".equals(userRole)) {

            JMenuItem mniUpdateCredentials = new JMenuItem("Update Credentials");
            mniUpdateCredentials.addActionListener(e -> searchPage.mniUpdateCredentialsActionPerformed(new java.awt.event.ActionEvent(this, ActionEvent.ACTION_PERFORMED, null)));

            // Pass the menu items into the EmployeeSearchPage
            searchPage.setPopupMenuItems(mniUpdateCredentials);
        }
        searchPage.setVisible(true);
    }//GEN-LAST:event_btnSearchAnEmployeeActionPerformed

    private void btnManageLeaveRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLeaveRequestsActionPerformed
        try {
            // Open ManageLeaveMenu
            new LeaveTablePage().setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(MainMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnManageLeaveRequestsActionPerformed

    private void btnAddNewEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmployeeActionPerformed
        new AddNewEmployeePage().setVisible(true);
    }//GEN-LAST:event_btnAddNewEmployeeActionPerformed

    private void configureMenu() {
        // Define which buttons should be visible for each role
        Set<JButton> visibleButtons = new HashSet<>();

        if (userRole.equals("Admin")) {
            visibleButtons.add(btnSearchAnEmployee);
            visibleButtons.add(btnManageLeaveRequests);
        } else if (userRole.equals("IT")) {
            visibleButtons.add(btnSearchAnEmployee);
            visibleButtons.add(btnAddNewEmployee);
        } else if (userRole.equals("Employee")) {
            visibleButtons.add(btnViewProfile);
            visibleButtons.add(btnComputePayroll);
            visibleButtons.add(btnApplyForLeave);
        }

        // Always keep Logout and Exit buttons visible
        visibleButtons.add(btnLogout);
        visibleButtons.add(btnExit);

        // Hide all buttons first, then only show the allowed ones
        for (Component component : pnlMain.getComponents()) {
            if (component instanceof JButton) {
                component.setVisible(visibleButtons.contains(component));
            }
        }

        pnlMain.revalidate(); // Refresh layout
        pnlMain.repaint();
        pack(); // Resize frame
    }

    /**
     * Displays a confirmation dialog before logging out and returning to the
     * login page.
     */
    private void logout() {
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            dispose();
            new LoginPage().setVisible(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmployee;
    private javax.swing.JButton btnApplyForLeave;
    private javax.swing.JButton btnComputePayroll;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageLeaveRequests;
    private javax.swing.JButton btnSearchAnEmployee;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JLabel lblMainMenuHeader;
    private javax.swing.JLabel lblMotorPhHeader;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
